### ISSUE TITLE
Error on grid-tie system without battery

### ISSUE THREAD

**Issue by 203agent203** [zbigniewmotyka/home-assistant-solplanet#17]
Hi there,
Installation failed with the error "failed setup, will retry. Error fetching data from API:'battery'".
I'm using the latest beta.
I don't have battery in my system.
Please let me know if you need any further logs.
Cheers,
T.

**Comment by zbigniewmotyka** [comment]
Which version have you installed? If you have 0.2.0-betaX, then it won't work for you. This version right now is used only for inverters supporting battery. Because of that, those releases are marked as pre-release to not be installed during integration update. The next beta release will contain some mechanisms to check battery support.

**Comment by zbigniewmotyka** [comment]
Use 0.1.x version for your setup

**Comment by Lafferfr** [comment]
How should I update to the newest Beta (I have Battery and Powermeter)?

**Comment by zbigniewmotyka** [comment]
> How should I update to the newest Beta (I have Battery and Powermeter)?

In hacs when you select integration installation you need to manually select version.

![Screenshot_20241022_194532_Home Assistant.jpg](https://github.com/user-attachments/assets/c52584fe-0931-4755-9596-055f56f12b08)
